name: Release to PyPI

on:
  workflow_dispatch:
  push:
    tags:
      - v*

jobs:
  release-pypi:
    - name: Publish package
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: ${{ env.GITHUB_NAME }}
        password: ${{ secrets.PYPI_API_TOKEN }}
