name: Run Poster Generate

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches:
      - main

env:
  # please change to your own config.
  # this actions generate only this year
  TYPE: 'ns, duolingo' # support strava/gpx/ns/cichang/shanbay/duolingo, Please change the 'pass' it to your own separated by commas
  ME: Yihong0618
  GITHUB_NAME: yihong0618
  GITHUB_EMAIL: zouzou0208@gmail.com

jobs:
  sync:
    name: Sync
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.6

      - name: Configure pip cache
        uses: actions/cache@v1
        id: pip-cache
        with:
          path: venv
          key: pip-1-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        if: steps.pip-cache.outputs.cache-hit != 'true'

      - name: Run sync ns script
        if: contains(env.TYPE, 'ns')
        run: |
          python cli.py --type ns --ns_session_token ${{ secrets.NS_SESSION_TOKEN }} --ns_device_id ${{ secrets.NS_DEVICE_ID }}

      - name: Run sync strava script
        if: contains(env.TYPE, 'strava')
        run: |
          python cli.py --type strava --strava_client_id ${{ secrets.STRAVA_CLIENT_ID }} --strava_client_secret ${{ secrets.STRAVA_CLIENT_SECRET }} --strava_refresh_token ${{ secrets.STRAVA_CLIENT_REFRESH_TOKEN }} 
  
      - name: Run sync shanbay script
        if: contains(env.TYPE, 'shanbay')
        run: |
          python cli.py --type shanbay -shanbay_user_name ${{ secrets.SHANBAY_USER_NAME }}   --special-color1 '#33C6A4' --special-color2  '#33C6A4'

      - name: Run sync duolingo script
        if: contains(env.TYPE, 'duolingo')
        run: |
          python cli.py --type duolingo --duolingo_user_name ${{ secrets.DUOLINGO_USER_NAME }}

      - name: Run sync cichang script
        if: contains(env.TYPE, 'cichang')
        run: |
          python cli.py --type cichang --cichang_user_name ${{ secrets.CICHANG_USER_NAME }} --cichang_password ${{ secrets.CICHANG_PASSWORD }} --me ${{ env.ME }}

      - name: Push new svg posters
        uses: github-actions-x/commit@v2.6
        with:
          github-token: ${{ secrets.G_T }}
          commit-message: "Add new runs"
          files: OUT_FOLDER/
          rebase: 'true'
          name: ${{ env.GITHUB_NAME }}
          email: ${{ env.GITHUB_EMAIL }}
